//! Security utility functions for VAULTEX.
//!
//! Provides constant-time comparison, secure random byte generation,
//! and memory wiping primitives. All implementations delegate to
//! libsodium (via sodiumoxide) to avoid homebrew crypto.

use sodiumoxide::utils;

/// Compares two byte slices in constant time.
///
/// Returns `true` if the slices are equal, `false` otherwise.
/// The comparison time does not depend on the content of the slices,
/// only on their length. If the slices have different lengths,
/// returns `false` (this comparison is not constant-time with
/// respect to length, only content).
///
/// Uses sodiumoxide's `memcmp` which wraps libsodium's
/// `sodium_memcmp`.
#[must_use]
pub fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    utils::memcmp(a, b)
}

/// Generates `len` bytes of cryptographically secure random data.
///
/// Uses sodiumoxide's `randombytes` which wraps libsodium's
/// `randombytes_buf` (backed by the OS CSPRNG).
///
/// # Panics
///
/// Panics in debug builds if all generated bytes are zero (extremely
/// unlikely but indicates a broken CSPRNG).
#[must_use]
pub fn secure_random_bytes(len: usize) -> Vec<u8> {
    let bytes = sodiumoxide::randombytes::randombytes(len);
    debug_assert!(
        len == 0 || bytes.iter().any(|&b| b != 0),
        "CSPRNG produced all-zero output — this indicates a broken random number generator"
    );
    bytes
}

/// Securely wipes the contents of a mutable byte slice.
///
/// Uses sodiumoxide's `memzero` which wraps libsodium's
/// `sodium_memzero`. This function is guaranteed not to be
/// optimized away by the compiler.
pub fn wipe_memory(data: &mut [u8]) {
    utils::memzero(data);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_constant_time_eq_equal_slices() {
        let a = b"hello vaultex";
        let b = b"hello vaultex";
        assert!(constant_time_eq(a, b));
    }

    #[test]
    fn test_constant_time_eq_different_slices() {
        let a = b"hello vaultex";
        let b = b"hello VAULTEX";
        assert!(!constant_time_eq(a, b));
    }

    #[test]
    fn test_constant_time_eq_different_lengths() {
        let a = b"short";
        let b = b"longer string";
        assert!(!constant_time_eq(a, b));
    }

    #[test]
    fn test_constant_time_eq_empty_slices() {
        assert!(constant_time_eq(&[], &[]));
    }

    #[test]
    fn test_constant_time_eq_single_bit_difference() {
        let a = [0x00u8; 32];
        let mut b = [0x00u8; 32];
        b[31] = 0x01;
        assert!(!constant_time_eq(&a, &b));
    }

    #[test]
    fn test_secure_random_bytes_correct_length() {
        sodiumoxide::init().unwrap();
        let bytes = secure_random_bytes(32);
        assert_eq!(bytes.len(), 32);
    }

    #[test]
    fn test_secure_random_bytes_non_zero() {
        sodiumoxide::init().unwrap();
        let bytes = secure_random_bytes(32);
        // At least one byte should be non-zero (probability of all zeros is 2^-256)
        assert!(bytes.iter().any(|&b| b != 0));
    }

    #[test]
    fn test_secure_random_bytes_non_repeating() {
        sodiumoxide::init().unwrap();
        let a = secure_random_bytes(32);
        let b = secure_random_bytes(32);
        // Two random 32-byte outputs should differ (probability of collision is 2^-256)
        assert_ne!(a, b);
    }

    #[test]
    fn test_secure_random_bytes_empty() {
        sodiumoxide::init().unwrap();
        let bytes = secure_random_bytes(0);
        assert!(bytes.is_empty());
    }

    #[test]
    fn test_secure_random_bytes_large() {
        sodiumoxide::init().unwrap();
        let bytes = secure_random_bytes(1024);
        assert_eq!(bytes.len(), 1024);
        // Should have reasonable entropy -- at least some bytes differ
        let unique_bytes: std::collections::HashSet<u8> = bytes.iter().copied().collect();
        assert!(unique_bytes.len() > 1);
    }

    #[test]
    fn test_wipe_memory_zeroes_data() {
        let mut data = [0xFFu8; 64];
        wipe_memory(&mut data);
        assert!(
            data.iter().all(|&b| b == 0),
            "wipe_memory must zero all bytes"
        );
    }

    #[test]
    fn test_wipe_memory_empty_slice() {
        // Should not panic on empty slice
        let mut data: [u8; 0] = [];
        wipe_memory(&mut data);
    }

    #[test]
    fn test_wipe_memory_single_byte() {
        let mut data = [0xABu8; 1];
        wipe_memory(&mut data);
        assert_eq!(data[0], 0);
    }

    #[test]
    fn test_wipe_memory_vec() {
        let mut data = vec![0xCDu8; 256];
        wipe_memory(&mut data);
        assert!(data.iter().all(|&b| b == 0));
    }
}
